// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — `migrate deploy`
    // takes a Postgres advisory lock for the duration of the run, and
    // PgBouncer-style transaction-mode poolers (what Neon's default
    // DATABASE_URL goes through) don't preserve session state across pooled
    // connections, so the lock acquisition just times out. The app's own
    // runtime Prisma client (src/lib/prisma.ts) is unaffected by this file —
    // it builds its adapter directly from DATABASE_URL for normal queries,
    // where pooling is exactly what you want.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
